apiVersion: v1
kind: Service
metadata:
  name: dev-command-service
  namespace: dev
  labels:
    app: dev
spec:
  selector:
    app: dev
    tier: command
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev-command-deployment
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dev
        tier: command
    spec:
      containers:
      - name: command
        image: logcorneredusync.azurecr.io/logcorner-edusync-speech-presentation:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: registrysecret