apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: __namespace__
  name: command-database-deployment
  labels:
    app: __namespace__
    tier: command-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: __namespace__
        tier: database
    spec:
      containers:
      - name:  command-database-container
        image: __ContainerRegistry__/logcorner-edusync-speech-presentation-data
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "PassW0rd"
        - name: ACCEPT_EULA
          value: "Y"
      imagePullSecrets:
        - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  namespace: __namespace__
  name: command-database-service
  labels:
    app: __namespace__
    tier: command-db
spec:
  ports:
  - name: sqlserver
    port: 1433
    targetPort: 1433
  selector:
    app: __namespace__
    tier: database
  type: LoadBalancer
